### ISSUE TITLE
LDAP search did not return a email

### ISSUE THREAD

**Issue by kurian-dm** [NaturalHistoryMuseum/ckanext-ldap#80]
Why is it compulsory to setup the email id for a user in LDAP. I ask this because I am not able to login in to the front end using a LDAP user. I get the following error.

"LDAP search did not return a email"

I am using SimpleAD and we don't have email setup.

**Expected Behaviour**
What you expected to happen instead.
When signing into CKAN as an LDAP user and if the user does not have an email setup in LDAP, the user should be allowed to login.

**To Reproduce**
Steps to reproduce the bug.

1) Setup Simple AD
2) Setup an admin user . There is no option to provide email. So email will not be there by default.
3) I am running ckan on Kubernetes.
4) Log into LDAP with the User

You will get the following error in the CKAN pod logs.

"LDAP search did not return a email"

**Comment by jrdh** [comment]
Hi @kurian-dm - this will be because the CKAN User model the LDAP User entity is attached to requires an email address (https://github.com/ckan/ckan/blob/master/ckan/logic/schema.py#L430) so in order to create a CKAN User to attach the LDAP User to, we have to get an email address from the auth request.
